import './globals.css'
import { Inter, Luckiest_Guy } from 'next/font/google'
import NavBar from '@/components/NavBar'


const inter = Inter({ subsets: ['latin'] })

const luckiestGuy = Luckiest_Guy({
  subsets : ["latin"],
  variable : "--font-luckiest-guy",
  weight: "400"
})

export const metadata = {
  title: 'TodosApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
      <body className={`${luckiestGuy.variable}`}>
      <NavBar />
      {children}
      </body>

    </html>
  )
}
